quarkus:
  http:
    proxy:
      enable-forwarded-prefix: true
    cors: true
    port: 8080
    test-port: 8081
    host: 0.0.0.0
    root-path: /identity-provider-api
  application:
    name: Identity Provider service
   # version: ${FOODHOUSE_VERSION}
  console:
    color: true
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    reactive:
      url: postgresql://${DB_HOST}:5432/slurpanize_db
      max-size: 20
  log:
    level: INFO

# => OpenAPI settings
mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Identity Provider service
          #version: ${FOODHOUSE_VERSION}
          description: Identity provider for Slurpanize
